#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"

SERVICE_NAME="${SERVICE_NAME:-com.ganxing.codexbridge-weixin.service}"
SERVICE_DESCRIPTION="${SERVICE_DESCRIPTION:-CodexBridge WeChat Bridge}"
SYSTEMD_UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
SYSTEMD_UNIT_PATH="${SYSTEMD_UNIT_DIR}/${SERVICE_NAME}"
SERVICE_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/codexbridge"
SERVICE_ENV_FILE="${SERVICE_ENV_FILE:-${SERVICE_CONFIG_DIR}/weixin.service.env}"
SERVICE_LOG_DIR="${SERVICE_LOG_DIR:-$HOME/.codexbridge/logs}"
SERVICE_STDOUT_LOG="${SERVICE_STDOUT_LOG:-${SERVICE_LOG_DIR}/weixin-bridge.out.log}"
SERVICE_STDERR_LOG="${SERVICE_STDERR_LOG:-${SERVICE_LOG_DIR}/weixin-bridge.err.log}"
STATE_DIR="${CODEXBRIDGE_STATE_DIR:-$HOME/.codexbridge}"
EXAMPLE_ENV_FILE="${ROOT_DIR}/config/examples/weixin.service.env.example"
UNIT_TEMPLATE_PATH="${ROOT_DIR}/ops/systemd/com.ganxing.codexbridge-weixin.service.template"

USER_NAME="${USER:-$(id -un)}"
LOGNAME_VALUE="${LOGNAME:-$USER_NAME}"
HOME_VALUE="${HOME}"

NODE_BIN="${NODE_BIN:-$(command -v node || true)}"
NPM_BIN="${NPM_BIN:-$(command -v npm || true)}"
NODE_DIR=""
if [[ -n "${NODE_BIN}" ]]; then
  NODE_DIR="$(cd "$(dirname "${NODE_BIN}")" && pwd)"
fi
LOCAL_BIN_DIR="${HOME}/.local/bin"
DEFAULT_SYSTEM_PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
PATH_VALUE="${DEFAULT_SYSTEM_PATH}"
if [[ -d "${LOCAL_BIN_DIR}" ]]; then
  PATH_VALUE="${LOCAL_BIN_DIR}:${PATH_VALUE}"
fi
if [[ -n "${NODE_DIR}" ]]; then
  PATH_VALUE="${NODE_DIR}:${PATH_VALUE}"
fi

CODEX_BIN_DEFAULT="${CODEX_REAL_BIN:-}"
if [[ -z "${CODEX_BIN_DEFAULT}" && -n "${NODE_DIR}" && -x "${NODE_DIR}/codex" ]]; then
  CODEX_BIN_DEFAULT="${NODE_DIR}/codex"
fi
if [[ -z "${CODEX_BIN_DEFAULT}" ]]; then
  CODEX_BIN_DEFAULT="$(PATH="${PATH_VALUE}" command -v codex || true)"
fi

require_linux() {
  if [[ "$(uname -s)" != "Linux" ]]; then
    echo "systemd user services are only supported on Linux" >&2
    exit 1
  fi
}

require_systemctl() {
  if ! command -v systemctl >/dev/null 2>&1; then
    echo "systemctl not found" >&2
    exit 1
  fi
}

require_journalctl() {
  if ! command -v journalctl >/dev/null 2>&1; then
    echo "journalctl not found" >&2
    exit 1
  fi
}

require_node_bin() {
  if [[ -z "${NODE_BIN}" ]]; then
    echo "node not found in PATH" >&2
    exit 1
  fi
}

require_unit_installed() {
  if [[ ! -f "${SYSTEMD_UNIT_PATH}" ]]; then
    echo "systemd unit is not installed: ${SYSTEMD_UNIT_PATH}" >&2
    exit 1
  fi
}

find_single_weixin_account_id() {
  local accounts_dir="${STATE_DIR}/weixin/accounts"
  local candidates=()
  local file
  if [[ ! -d "${accounts_dir}" ]]; then
    return 0
  fi
  while IFS= read -r -d '' file; do
    local basename
    basename="$(basename "${file}")"
    case "${basename}" in
      *.context-tokens.json|*.sync.json) continue ;;
      *.json) candidates+=("${basename%.json}") ;;
    esac
  done < <(find "${accounts_dir}" -maxdepth 1 -type f -name '*.json' -print0 | sort -z)

  if [[ "${#candidates[@]}" -eq 1 ]]; then
    printf '%s' "${candidates[0]}"
  fi
}

ensure_service_dirs() {
  mkdir -p "${SYSTEMD_UNIT_DIR}" "${SERVICE_CONFIG_DIR}" "${SERVICE_LOG_DIR}"
}

ensure_service_env_file() {
  ensure_service_dirs
  if [[ -f "${SERVICE_ENV_FILE}" ]]; then
    return
  fi

  local account_id
  account_id="$(find_single_weixin_account_id || true)"

  cat > "${SERVICE_ENV_FILE}" <<EOF
# Generated by scripts/service/install-systemd-user.sh
# Safe to edit after install.

WEIXIN_ACCOUNT_ID=${account_id}
WEIXIN_DM_POLICY=open
WEIXIN_GROUP_POLICY=disabled

CODEX_DEFAULT_PROVIDER_PROFILE_ID=openai-default
CODEX_REAL_BIN=${CODEX_BIN_DEFAULT}

CODEXBRIDGE_DEBUG_WEIXIN=0
EOF

  if [[ -f "${EXAMPLE_ENV_FILE}" ]]; then
    cat >> "${SERVICE_ENV_FILE}" <<'EOF'

# Optional values:
# - copy more keys from config/examples/weixin.service.env.example when needed
EOF
  fi
}

render_unit_file() {
  ensure_service_dirs
  python3 - <<'PY' "${UNIT_TEMPLATE_PATH}" "${SYSTEMD_UNIT_PATH}" "${ROOT_DIR}" "${NODE_BIN}" "${SERVICE_ENV_FILE}" "${PATH_VALUE}" "${HOME_VALUE}" "${USER_NAME}" "${LOGNAME_VALUE}" "${STATE_DIR}" "${SERVICE_DESCRIPTION}" "${SERVICE_STDOUT_LOG}" "${SERVICE_STDERR_LOG}"
import pathlib
import sys

(template_path,
 output_path,
 root_dir,
 node_bin,
 env_file,
 path_value,
 home_value,
 user_name,
 logname_value,
 state_dir,
 service_description,
 stdout_log,
 stderr_log) = sys.argv[1:]

template = pathlib.Path(template_path).read_text()
replacements = {
    "__SERVICE_DESCRIPTION__": service_description,
    "__ROOT_DIR__": root_dir,
    "__NODE_BIN__": node_bin,
    "__ENV_FILE__": env_file,
    "__PATH__": path_value,
    "__HOME__": home_value,
    "__USER__": user_name,
    "__LOGNAME__": logname_value,
    "__STATE_DIR__": state_dir,
    "__STDOUT_LOG__": stdout_log,
    "__STDERR_LOG__": stderr_log,
}
for key, value in replacements.items():
    template = template.replace(key, value)
pathlib.Path(output_path).write_text(template)
PY
}

stop_manual_weixin_runtime() {
  pkill -f '/home/ubuntu/dev/CodexBridge/src/cli.ts weixin serve' 2>/dev/null || true
}
