#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"

LABEL="${LABEL:-com.ganxing.codexbridge-weixin}"
PLIST_DIR="${HOME}/Library/LaunchAgents"
PLIST_PATH="${PLIST_DIR}/${LABEL}.plist"
STATE_DIR="${CODEXBRIDGE_STATE_DIR:-${HOME}/.codexbridge}"
CONFIG_DIR="${XDG_CONFIG_HOME:-${HOME}/.config}/codexbridge"
ENV_FILE="${SERVICE_ENV_FILE:-${CONFIG_DIR}/weixin.service.env}"
LOG_DIR="${STATE_DIR}/logs"
STDOUT_LOG="${SERVICE_STDOUT_LOG:-${LOG_DIR}/weixin-bridge.out.log}"
STDERR_LOG="${SERVICE_STDERR_LOG:-${LOG_DIR}/weixin-bridge.err.log}"
NODE_BIN="${NODE_BIN:-$(command -v node || true)}"
CODEX_BIN_DEFAULT="${CODEX_REAL_BIN:-$(command -v codex || true)}"
DEFAULT_CWD="${CODEXBRIDGE_DEFAULT_CWD:-}"

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "launchd user services are only supported on macOS" >&2
  exit 1
fi
if [[ -z "${NODE_BIN}" ]]; then
  echo "node not found in PATH" >&2
  exit 1
fi

mkdir -p "${PLIST_DIR}" "${CONFIG_DIR}" "${LOG_DIR}"

if [[ ! -f "${ENV_FILE}" ]]; then
  cat > "${ENV_FILE}" <<EOF
# Generated by scripts/service/install-launchd-user.sh
# Safe to edit after install.

WEIXIN_ACCOUNT_ID=
WEIXIN_DM_POLICY=open
WEIXIN_GROUP_POLICY=disabled

CODEX_DEFAULT_PROVIDER_PROFILE_ID=openai-default
CODEX_REAL_BIN=${CODEX_BIN_DEFAULT}

CODEXBRIDGE_DEBUG_WEIXIN=0
EOF
fi

python3 - <<'PY' "${PLIST_PATH}" "${LABEL}" "${NODE_BIN}" "${ROOT_DIR}" "${STATE_DIR}" "${ENV_FILE}" "${STDOUT_LOG}" "${STDERR_LOG}" "${DEFAULT_CWD}"
import plistlib
import sys

plist_path, label, node_bin, root_dir, state_dir, env_file, stdout_log, stderr_log, default_cwd = sys.argv[1:]
args = [
    node_bin,
    f"{root_dir}/scripts/service/run-weixin-service.mjs",
    "--root-dir", root_dir,
    "--state-dir", state_dir,
    "--env-file", env_file,
]
if default_cwd:
    args.extend(["--cwd", default_cwd])
payload = {
    "Label": label,
    "ProgramArguments": args,
    "WorkingDirectory": root_dir,
    "RunAtLoad": True,
    "KeepAlive": True,
    "StandardOutPath": stdout_log,
    "StandardErrorPath": stderr_log,
    "EnvironmentVariables": {
        "HOME": __import__("os").path.expanduser("~"),
        "PATH": "/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin",
    },
}
with open(plist_path, "wb") as handle:
    plistlib.dump(payload, handle)
PY

launchctl bootout "gui/${UID}" "${PLIST_PATH}" >/dev/null 2>&1 || true
launchctl bootstrap "gui/${UID}" "${PLIST_PATH}"
launchctl enable "gui/${UID}/${LABEL}"
launchctl kickstart -k "gui/${UID}/${LABEL}"

echo "Installed ${PLIST_PATH}"
echo "Environment file: ${ENV_FILE}"
echo "Stdout log: ${STDOUT_LOG}"
echo "Stderr log: ${STDERR_LOG}"
