param(
  [string]$TaskName = "CodexBridge-Weixin",
  [string]$RootDir = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path,
  [string]$StateDir = "",
  [string]$EnvFile = "",
  [string]$HomeDir = "",
  [string]$DefaultCwd = "",
  [switch]$AtStartup
)

$ErrorActionPreference = "Stop"

function Find-CommandPath([string[]]$Names) {
  foreach ($Name in $Names) {
    $Command = Get-Command $Name -ErrorAction SilentlyContinue
    if ($Command) {
      return $Command.Source
    }
  }
  return ""
}

function Resolve-ServiceHomeDir([string]$RequestedHomeDir, [string]$ResolvedRootDir) {
  if ($RequestedHomeDir) {
    $Resolved = Resolve-Path $RequestedHomeDir -ErrorAction SilentlyContinue
    if ($Resolved) {
      return $Resolved.Path
    }
    return $RequestedHomeDir
  }

  if ($env:CODEXBRIDGE_SERVICE_HOME) {
    $Resolved = Resolve-Path $env:CODEXBRIDGE_SERVICE_HOME -ErrorAction SilentlyContinue
    if ($Resolved) {
      return $Resolved.Path
    }
    return $env:CODEXBRIDGE_SERVICE_HOME
  }

  $CurrentIdentity = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
  if ($CurrentIdentity -ne "NT AUTHORITY\SYSTEM" -and $env:USERPROFILE) {
    return $env:USERPROFILE
  }

  $RootMatch = [regex]::Match($ResolvedRootDir, "^[A-Za-z]:\\Users\\[^\\]+")
  if ($RootMatch.Success) {
    return $RootMatch.Value
  }

  try {
    $LoggedOnUser = (Get-CimInstance Win32_ComputerSystem).UserName
    if ($LoggedOnUser -and $LoggedOnUser.Contains("\")) {
      $UserName = $LoggedOnUser.Split("\")[-1]
      $Candidate = Join-Path (Join-Path $env:SystemDrive "Users") $UserName
      if (Test-Path $Candidate) {
        return $Candidate
      }
    }
  } catch {}

  if ($env:USERPROFILE) {
    return $env:USERPROFILE
  }

  throw "Could not resolve service home directory. Pass -HomeDir explicitly."
}

function Resolve-ServiceAppData([string]$ResolvedHomeDir) {
  if ($env:APPDATA -and $env:APPDATA -notlike "*\systemprofile\*") {
    return $env:APPDATA
  }
  return Join-Path $ResolvedHomeDir "AppData\Roaming"
}

$NodeBin = Find-CommandPath @("node.exe", "node")
if (-not $NodeBin) {
  throw "node was not found in PATH"
}

$HomeDir = Resolve-ServiceHomeDir $HomeDir $RootDir
if (-not $StateDir) {
  $StateDir = Join-Path $HomeDir ".codexbridge"
}
if (-not $EnvFile) {
  $EnvFile = Join-Path (Resolve-ServiceAppData $HomeDir) "codexbridge\weixin.service.env"
}

$PublicCodexBin = "C:\Users\Public\Tools\Codex\codex.exe"
$CodexBin = if (Test-Path -LiteralPath $PublicCodexBin) {
  $PublicCodexBin
} else {
  Find-CommandPath @("codex.exe", "codex.cmd", "codex.bat", "codex")
}
$ConfigDir = Split-Path -Parent $EnvFile
$LogDir = Join-Path $StateDir "logs"
$StdoutLog = Join-Path $LogDir "weixin-bridge.out.log"
$StderrLog = Join-Path $LogDir "weixin-bridge.err.log"
$CodexHome = Join-Path $HomeDir ".codex"

New-Item -ItemType Directory -Force -Path $ConfigDir, $LogDir | Out-Null

if (-not (Test-Path $EnvFile)) {
  @(
    "# Generated by scripts/service/install-windows-task.ps1",
    "# Safe to edit after install.",
    "",
    "WEIXIN_ACCOUNT_ID=",
    "WEIXIN_DM_POLICY=open",
    "WEIXIN_GROUP_POLICY=disabled",
    "",
    "CODEX_DEFAULT_PROVIDER_PROFILE_ID=openai-default",
    "CODEX_HOME=$CodexHome",
    "CODEX_REAL_BIN=$CodexBin",
    "",
    "CODEXBRIDGE_DEBUG_WEIXIN=0"
  ) | Set-Content -Encoding UTF8 -Path $EnvFile
} else {
  $EnvContent = Get-Content -Path $EnvFile -Raw -Encoding UTF8
  if ($EnvContent -notmatch "(?m)^CODEX_HOME=") {
    Add-Content -Encoding UTF8 -Path $EnvFile -Value "CODEX_HOME=$CodexHome"
  }
}

$Runner = Join-Path $RootDir "scripts\service\run-weixin-service.mjs"
$Arguments = @(
  "`"$Runner`"",
  "--root-dir", "`"$RootDir`"",
  "--home-dir", "`"$HomeDir`"",
  "--state-dir", "`"$StateDir`"",
  "--env-file", "`"$EnvFile`"",
  "--stdout-log", "`"$StdoutLog`"",
  "--stderr-log", "`"$StderrLog`""
)
if ($DefaultCwd) {
  $Arguments += @("--cwd", "`"$DefaultCwd`"")
}

$Action = New-ScheduledTaskAction -Execute $NodeBin -Argument ($Arguments -join " ")
$CurrentIdentity = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
$RunAsSystem = $AtStartup -or $CurrentIdentity -eq "NT AUTHORITY\SYSTEM"

if ($RunAsSystem) {
  $Trigger = New-ScheduledTaskTrigger -AtStartup
} else {
  $Trigger = New-ScheduledTaskTrigger -AtLogOn -User $CurrentIdentity
}
$Settings = New-ScheduledTaskSettingsSet `
  -AllowStartIfOnBatteries `
  -DontStopIfGoingOnBatteries `
  -ExecutionTimeLimit (New-TimeSpan -Days 3650) `
  -MultipleInstances IgnoreNew `
  -RestartCount 999 `
  -RestartInterval (New-TimeSpan -Minutes 1) `
  -StartWhenAvailable

if ($RunAsSystem) {
  $Principal = New-ScheduledTaskPrincipal -UserId "NT AUTHORITY\SYSTEM" -LogonType ServiceAccount -RunLevel Highest
} else {
  $Principal = New-ScheduledTaskPrincipal -UserId $CurrentIdentity -LogonType Interactive -RunLevel Limited
}

$ExistingTask = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($ExistingTask -and $ExistingTask.State -eq "Running") {
  Stop-ScheduledTask -TaskName $TaskName
  $StopDeadline = [DateTime]::UtcNow.AddSeconds(15)
  do {
    Start-Sleep -Milliseconds 250
    $ExistingTask = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
  } while ($ExistingTask -and $ExistingTask.State -eq "Running" -and [DateTime]::UtcNow -lt $StopDeadline)

  if ($ExistingTask -and $ExistingTask.State -eq "Running") {
    throw "Timed out while stopping scheduled task: $TaskName"
  }
}

Get-CimInstance Win32_Process -Filter "name = 'node.exe'" |
  Where-Object {
    $_.CommandLine -like "*CodexBridge*" -and
    $_.CommandLine -like "*weixin serve*" -and
    $_.CommandLine -notlike "*run-weixin-service.mjs*"
  } |
  ForEach-Object {
    Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue
  }

Register-ScheduledTask -TaskName $TaskName -Action $Action -Trigger $Trigger -Settings $Settings -Principal $Principal -Force | Out-Null
Start-ScheduledTask -TaskName $TaskName

Write-Host "Installed scheduled task: $TaskName"
Write-Host "Run as: $($Principal.UserId)"
Write-Host "Home dir: $HomeDir"
Write-Host "Environment file: $EnvFile"
Write-Host "Stdout log: $StdoutLog"
Write-Host "Stderr log: $StderrLog"
Write-Host "Status: powershell -ExecutionPolicy Bypass -File scripts/service/status-windows-task.ps1"
